### ISSUE TITLE
macFuse 5.0.7 kernel extension cannot be approved after upgrading to macOS 15.6.1

### ISSUE THREAD

**Issue by Franck177** [osxfuse/osxfuse#1125]
May be a known issue .... : 

After upgrading to MacOS 15.6.1 the system prompts for for approval of Benjamin Fleischer’s software in System Settings > Privacy & Security. However, even after clicking "Approve" and restarting the Mac, the approval is not effective: the Benjamin Fleischer button remains grayed out (unclickable).

After installing macFUSE (version 5.0.7) from the official website, the issue remains the same.

**Actual behavior and context :**
 
- Running **kextstat | grep fuse** 
---> shows no loaded macFUSE extensions.

- Manual loading via **sudo kmutil load -b io.macfuse.filesystems.macfuse.23** fails with 
---> "Error Domain=KMErrorDomain Code=27 "Extension with identifiers io.macfuse.filesystems.macfuse.23 not approved to load. Please approve using System Settings." UserInfo={NSLocalizedDescription=Extension with identifiers io.macfuse.filesystems.macfuse.23 not approved to load. Please approve using System Settings.}"

- Output of **codesign -dv /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext** is 
---> Executable=/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext/Contents/MacOS/macfuse
Identifier=io.macfuse.filesystems.macfuse.23
Format=bundle with Mach-O universal (x86_64 arm64e)
CodeDirectory v=20200 size=513 flags=0x0(none) hashes=10+3 location=embedded
Signature size=9075
Timestamp=30 Sep 2025 at 01:21:31
Info.plist entries=19
TeamIdentifier=3T5GSNBU6W
Sealed Resources version=2 rules=13 files=0
Internal requirements count=1 size=228

- Output of **systemextensionsctl list** is :
---> 0 extension(s)

- **sudo /usr/bin/profiles -L -o stdout** returns
---> There are no configuration profiles installed in the system domain
{
}

Thank you for your help.

**Comment by mintedPearl** [comment]
Confirmed. Purchased new Mac today, Sequoia 15.6, unable to approve as stated above. 

Thank you for your work all, I love this tool and appreciate the work you do to provide it.

**Comment by bfleischer** [comment]
> After upgrading to MacOS 15.6.1 the system prompts for for approval of Benjamin Fleischer’s software in System Settings > Privacy & Security. However, even after clicking "Approve" and restarting the Mac, the approval is not effective: the Benjamin Fleischer button remains grayed out (unclickable).

Could you pleases post a screenshot?

I can confirm that macFUSE 5.0.7 works properly on macOS 15. This is almost certainly not a general issue or a bug in macFUSE. In all previous cases I’ve investigated, kernel extension loading problems were caused by issues specific to the individual Mac.

Could you please try to go through the approval process, restart your Mac when prompted to and then run the following command in Terminal. It will print the log messages from the kernelmanager macOS subsystem.

`kmutil log show`

The logs might provide a clue as to why the kernel extension cannot be loaded.

> Output of systemextensionsctl list is :
> ---> 0 extension(s)

This command lists only certain system extensions, not kernel extensions. This means it's not relevant for macFUSE.

Just to make sure, are you booting from an external volume or are you trying to use macFUSE in a virtual machine? Both use cases are not supported by macOS. It's not a macFUSE limitation.

**Comment by bfleischer** [comment]
> Confirmed. Purchased new Mac today, Sequoia 15.6, unable to approve as stated above.

Did you follow the instructions on https://github.com/macfuse/macfuse/wiki/Getting-Started? If so, which step does not work for you?

**Comment by Franck177** [comment]
After upgrading to MacOS 15.6.1 the system prompts for for approval of Benjamin Fleischer’s software in System Settings > Privacy & Security. However, even after clicking "Approve" and restarting the Mac, the approval is not effective: the Benjamin Fleischer button remains grayed out (unclickable).


> > After upgrading to MacOS 15.6.1 the system prompts for for approval of Benjamin Fleischer’s software in System Settings > Privacy & Security. However, even after clicking "Approve" and restarting the Mac, the approval is not effective: the Benjamin Fleischer button remains grayed out (unclickable).
> 
> Could you pleases post a screenshot?
> 

<img width="705" height="496" alt="Image" src="https://github.com/user-attachments/assets/25c4f76e-b159-47ac-a909-8b5b91594622" />

Translation of this french message : The system software of the following developers have been updated and the system must be restarted before using them 

Notice : restarting the system is useless, the same errors remains after having rebooted
 
> I can confirm that macFUSE 5.0.7 works properly on macOS 15. This is almost certainly not a general issue or a bug in macFUSE. In all previous cases I’ve investigated, kernel extension loading problems were caused by issues specific to the individual Mac.
>  
> Could you please try to go through the approval process, restart your Mac when prompted to 

**Done**

> and then run the following command in Terminal. It will print the log messages from the kernelmanager macOS subsystem.
> 
> `kmutil log show`
> 
> The logs might provide a clue as to why the kernel extension cannot be loaded.
>
There are several errors, 
**1st one :** 
2025-11-08 11:12:26.501588+0100 0x1460fe   Default     0x0                  133    0    kernelmanagerd: Errors thrown: <private> 1 <private>
2025-11-08 11:12:26.501603+0100 0x1460fe   Error       0x0                  133    0    kernelmanagerd: failed to load/rebuild extensions: Could not find: Extension with identifier 'com.apple.driver.AppleKIS' not found
 
**other ones :** 
2025-11-10 10:50:34.612728+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: Handling loadOrRebuildRequest: 
paths: ["/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext"],
identifiers: [],
personalityNames: [],
extraRepositories: [],
dependencyKextsAndRepositories: [],
flags: [clientPrivileged, ]
2025-11-10 10:50:34.613092+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: [FullLoadOrRebuildRequestHandler] Request: <private>
2025-11-10 10:50:34.613094+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: loading existing auxiliary collection contents from stashed instructions
2025-11-10 10:50:34.618229+0100 0x28d18c   Activity    0x7233d8             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:50:34.618311+0100 0x28d18c   Activity    0x7233d9             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:50:34.618369+0100 0x28d18c   Activity    0x7233da             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:50:34.619091+0100 0x28d18c   Activity    0x7233db             78495  0    kernelmanager_helper: (Security) SecTrustSettingsXPCRead
2025-11-10 10:50:34.619488+0100 0x28d18c   Activity    0x7233dc             78495  0    kernelmanager_helper: (Security) SecKeychainAddCallback
2025-11-10 10:50:34.619572+0100 0x28d18c   Activity    0x7233dd             78495  0    kernelmanager_helper: (Security) SecTrustSettingsXPCRead
2025-11-10 10:50:34.620266+0100 0x28d18c   Activity    0x7233de             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:50:34.621352+0100 0x28d18c   Activity    0x7233df             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:50:34.623157+0100 0x28d18c   Activity    0x7233f0             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:50:34.623224+0100 0x28d18c   Activity    0x7233f1             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:50:34.623268+0100 0x28d18c   Activity    0x7233f2             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:50:34.623706+0100 0x28d18c   Activity    0x7233f3             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:50:34.623927+0100 0x28d18c   Activity    0x7233f4             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:50:34.627063+0100 0x28d18c   Activity    0x7233f5             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:50:34.627127+0100 0x28d18c   Activity    0x7233f6             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:50:34.627170+0100 0x28d18c   Activity    0x7233f7             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:50:34.627629+0100 0x28d18c   Activity    0x7233f8             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:50:34.627831+0100 0x28d18c   Activity    0x7233f9             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:50:34.629818+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: Validating extension at <private>
2025-11-10 10:50:34.631483+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: (libxpc.dylib) [com.apple.xpc:connection] [0x5fcfd0000] activating connection: mach=true listener=false peer=false name=com.apple.lsd.mapdb
2025-11-10 10:50:34.634322+0100 0x28d18c   Activity    0x7233fa             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:50:34.634387+0100 0x28d18c   Activity    0x7233fb             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:50:34.636329+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: Validating extension at <private>
2025-11-10 10:50:34.637198+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: [com.apple.kernelmanagerd.logging:LoadRequestResolution] checking bundle path /Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext for Kext io.macfuse.filesystems.macfuse.23 v5.1.1 in executable kext bundle io.macfuse.filesystems.macfuse.23 at /Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext
2025-11-10 10:50:34.637217+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: [com.apple.kernelmanagerd.logging:LoadRequestResolution] checking unstaged bundle path /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext for Kext io.macfuse.filesystems.macfuse.23 v5.1.1 in executable kext bundle io.macfuse.filesystems.macfuse.23 at /Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext
2025-11-10 10:50:34.637279+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: [com.apple.kernelmanagerd.logging:LoadRequestResolution] checking bundle path /Library/Apple/System/Library/Extensions/AppleMobileDevice.kext for Kext com.apple.driver.AppleMobileDevice v4.0 in codeless kext bundle com.apple.driver.AppleMobileDevice at /Library/Apple/System/Library/Extensions/AppleMobileDevice.kext
2025-11-10 10:50:34.637330+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: [com.apple.kernelmanagerd.logging:LoadRequestResolution] checking unstaged bundle path /Library/Apple/System/Library/Extensions/AppleMobileDevice.kext for Kext com.apple.driver.AppleMobileDevice v4.0 in codeless kext bundle com.apple.driver.AppleMobileDevice at /Library/Apple/System/Library/Extensions/AppleMobileDevice.kext
2025-11-10 10:50:34.637585+0100 0x28d18c   Error       0x0                  78495  0    kernelmanager_helper: LimitedDiskManagerClient cannot prevent removal of /dev/disk3s2
2025-11-10 10:50:34.637586+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: expecting to find <private> mounted at /System/Volumes/Preboot/
2025-11-10 10:50:34.638649+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_linked_manifest: entry
2025-11-10 10:50:34.638651+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_linked_manifest_ex: entry
2025-11-10 10:50:34.638698+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_blessed_local_policy_nonce_digest: entry
2025-11-10 10:50:34.639011+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: SEP command 14 returned 0
2025-11-10 10:50:34.639013+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_blessed_local_policy_nonce_digest: exit: success (0)
2025-11-10 10:50:34.639153+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: reading blessed linked manifest /System/Volumes/iSCPreboot/991E65A9-8259-4241-87BB-52D01B7A2290/LocalPolicy/8FDF85DFCF715506D9383D0105F5A307F0E37C42302AB9B3BBDA73B8C0D0CBA4DF181187864542DFAB334051DC89E31A.auxk.im4m
2025-11-10 10:50:34.639264+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_blessed_local_policy_nonce_digest: entry
2025-11-10 10:50:34.639337+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: SEP command 14 returned 0
2025-11-10 10:50:34.639338+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_blessed_local_policy_nonce_digest: exit: success (0)
2025-11-10 10:50:34.639375+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: reading blessed macOS local policy /System/Volumes/iSCPreboot/991E65A9-8259-4241-87BB-52D01B7A2290/LocalPolicy/8FDF85DFCF715506D9383D0105F5A307F0E37C42302AB9B3BBDA73B8C0D0CBA4DF181187864542DFAB334051DC89E31A.img4
2025-11-10 10:50:34.661475+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: SEP command 35 returned 0
2025-11-10 10:50:34.661478+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_linked_manifest_ex: exit: success (0)
2025-11-10 10:50:34.661478+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_linked_manifest: exit: success (0)
2025-11-10 10:50:34.661530+0100 0x28d18c   Error       0x0                  78495  0    kernelmanager_helper: LimitedDiskManagerClient cannot prevent removal of /dev/disk1s1
2025-11-10 10:50:34.661546+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: volume <private> is already mounted at /System/Volumes/iSCPreboot
2025-11-10 10:50:34.661958+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: BlessHandle created against /dev/disk3s5
2025-11-10 10:50:34.798095+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: expecting to find <private> mounted at /System/Volumes/Preboot/
2025-11-10 10:50:34.798237+0100 0x28d18c   Error       0x0                  78495  0    kernelmanager_helper: LimitedDiskManagerClient cannot prevent removal of /dev/disk1s1
2025-11-10 10:50:34.798252+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: volume <private> is already mounted at /System/Volumes/iSCPreboot
2025-11-10 10:50:34.798824+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: BlessHandle created against /dev/disk3s5
2025-11-10 10:50:34.798834+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_nsih: entry
2025-11-10 10:50:34.798834+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_nsih_ex: entry
2025-11-10 10:50:34.798835+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_local_policy_digest_tag_ex2: entry
2025-11-10 10:50:34.798838+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_blessed_local_policy_nonce_digest: entry
2025-11-10 10:50:34.798938+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: SEP command 14 returned 0
2025-11-10 10:50:34.798938+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_blessed_local_policy_nonce_digest: exit: success (0)
2025-11-10 10:50:34.798966+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: reading blessed macOS local policy /System/Volumes/iSCPreboot/991E65A9-8259-4241-87BB-52D01B7A2290/LocalPolicy/8FDF85DFCF715506D9383D0105F5A307F0E37C42302AB9B3BBDA73B8C0D0CBA4DF181187864542DFAB334051DC89E31A.img4
2025-11-10 10:50:34.810010+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: SEP command 61 returned 0
2025-11-10 10:50:34.810013+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_local_policy_digest_tag_ex2: exit: success (0)
2025-11-10 10:50:34.810013+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_nsih_ex: exit: success (0)
2025-11-10 10:50:34.810014+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_nsih: exit: success (0)
2025-11-10 10:50:34.810024+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: boot objects path: 991E65A9-8259-4241-87BB-52D01B7A2290/boot/C6566CB78B2B793B98009070C85F8664734B77022DD503754D6F579A8390A04F38B0BD8427EE21F492A98264C7EC459B
2025-11-10 10:50:34.810083+0100 0x28d18c   Error       0x0                  78495  0    kernelmanager_helper: LimitedDiskManagerClient cannot allow removal of /dev/disk1s1
2025-11-10 10:50:34.810234+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_local_policy_digest_tag: entry
2025-11-10 10:50:34.810234+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_local_policy_digest_tag_ex2: entry
2025-11-10 10:50:34.810236+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_blessed_local_policy_nonce_digest: entry
2025-11-10 10:50:34.810345+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: SEP command 14 returned 0
2025-11-10 10:50:34.810345+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_blessed_local_policy_nonce_digest: exit: success (0)
2025-11-10 10:50:34.810371+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: reading blessed macOS local policy /System/Volumes/iSCPreboot/991E65A9-8259-4241-87BB-52D01B7A2290/LocalPolicy/8FDF85DFCF715506D9383D0105F5A307F0E37C42302AB9B3BBDA73B8C0D0CBA4DF181187864542DFAB334051DC89E31A.img4
2025-11-10 10:50:34.821399+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: SEP command 61 returned 14
2025-11-10 10:50:34.821412+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_local_policy_digest_tag_ex2: exit: tag not found (14)
2025-11-10 10:50:34.821414+0100 0x28d18c   Default     0x0                  78495  30   kernelmanager_helper: (libbootpolicy.dylib) [com.apple.BootPolicy:Library] BootPolicy: bootpolicy_get_local_policy_digest_tag: exit: tag not found (14)
2025-11-10 10:50:34.821912+0100 0x28d18c   Error       0x0                  78495  0    kernelmanager_helper: LimitedDiskManagerClient cannot allow removal of /dev/disk3s2
2025-11-10 10:50:34.966206+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: loaded collection: boot kernel collection at /System/Volumes/Preboot/991E65A9-8259-4241-87BB-52D01B7A2290/boot/C6566CB78B2B793B98009070C85F8664734B77022DD503754D6F579A8390A04F38B0BD8427EE21F492A98264C7EC459B/System/Library/Caches/com.apple.kernelcaches/kernelcache
2025-11-10 10:50:34.966295+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: using boot collection: /System/Volumes/Preboot/991E65A9-8259-4241-87BB-52D01B7A2290/boot/C6566CB78B2B793B98009070C85F8664734B77022DD503754D6F579A8390A04F38B0BD8427EE21F492A98264C7EC459B/System/Library/Caches/com.apple.kernelcaches/kernelcache
2025-11-10 10:50:34.969883+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: Already have Kext com.apple.kpi.bsd v24.6.0 in loaded boot kernel collection, skipping...
2025-11-10 10:50:34.969886+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: Already have Kext com.apple.kpi.mach v24.6.0 in loaded boot kernel collection, skipping...
2025-11-10 10:50:34.969888+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: Already have Kext com.apple.kpi.unsupported v24.6.0 in loaded boot kernel collection, skipping...
2025-11-10 10:50:34.969890+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: Already have Kext com.apple.kpi.libkern v24.6.0 in loaded boot kernel collection, skipping...
2025-11-10 10:50:34.969892+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: Already have Kext com.apple.kpi.iokit v24.6.0 in loaded boot kernel collection, skipping...
2025-11-10 10:50:35.417779+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: Collection wrapped successfully into im4p
2025-11-10 10:50:35.420933+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: auxkc build requires reboot, calling out to syspolicyd
2025-11-10 10:50:35.420946+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: [com.apple.kernelmanagerd.logging:LoadRequestResolution] gathering approvals for: 
	/Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext
2025-11-10 10:50:35.467081+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: <private>
2025-11-10 10:50:35.467240+0100 0x28d18c   Default     0x0                  78495  0    kernelmanager_helper: [com.apple.kernelmanagerd.logging:LoadRequestResolution] Serviced request: 
approvalsRequiredFromSyspolicyd: true
newAuxiliaryContents: [Kext io.macfuse.filesystems.macfuse.23 v5.1.1 in executable kext bundle io.macfuse.filesystems.macfuse.23 at /Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext, Kext com.apple.driver.AppleMobileDevice v4.0 in codeless kext bundle com.apple.driver.AppleMobileDevice at /Library/Apple/System/Library/Extensions/AppleMobileDevice.kext]
directLoadPlatformExtensions: []
directLoadAuxiliaryExtensions: []
extensionsNeedingApproval: []
approvedUnbuiltExtensions: [Kext io.macfuse.filesystems.macfuse.23 v5.1.1 in executable kext bundle io.macfuse.filesystems.macfuse.23 at /Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext]
safebootBlockedExtensions: []
unsupportedExtensions: []
2025-11-10 10:50:35.471559+0100 0x28d182   Default     0x0                  133    0    kernelmanagerd: Errors thrown: <private> 1 <private>
2025-11-10 10:50:35.471564+0100 0x28d182   Error       0x0                  133    0    kernelmanagerd: failed to load/rebuild extensions: Extension with identifiers io.macfuse.filesystems.macfuse.23 not approved to load. Please approve using System Settings.
2025-11-10 10:50:35.472146+0100 0x28d182   Default     0x0                  133    0    kernelmanagerd: (libxpc.dylib) [com.apple.xpc:connection] [0x706d68640] invalidated because the client process (pid 78494) either cancelled the connection or exited
2025-11-10 10:50:35.472190+0100 0x28d182   Default     0x0                  133    0    kernelmanagerd: Connection with client pid 78494 invalidated.
2025-11-10 10:52:31.273377+0100 0x263aab   Default     0x0                  133    0    kernelmanagerd: incoming connection from pid 298
2025-11-10 10:52:31.273800+0100 0x263aab   Default     0x0                  133    0    kernelmanagerd: (libxpc.dylib) [com.apple.xpc:connection] [0x706d68640] activating connection: mach=false listener=false peer=true name=com.apple.KernelExtensionServer.peer[298].0x706d68640
2025-11-10 10:52:31.274378+0100 0x28dbee   Default     0x0                  133    0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] loadExtensions(withPaths:withIdentifiers:withPersonalityNames:withDependencyAndFolderPaths:options:withReply:): Loading paths: [], identifiers: ["io.macfuse.filesystems.macfuse.23"], personalityNames: []
2025-11-10 10:52:31.274493+0100 0x28dbee   Default     0x0                  133    0    kernelmanagerd: Handling loadOrRebuildRequest: <private>{public}s
2025-11-10 10:52:31.274506+0100 0x28dbee   Default     0x0                  133    0    kernelmanagerd: [LimitedLoadRequestHandler] Request: <private>
2025-11-10 10:52:31.274679+0100 0x28dbee   Default     0x0                  133    0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] [LimitedRequestProcessor] Processed request: 
requestedExts: []
followupRequest: 
paths: [],
identifiers: ["io.macfuse.filesystems.macfuse.23"],
personalityNames: [],
extraRepositories: [],
dependencyKextsAndRepositories: [],
flags: [disallowAuth, clientPrivileged, ]
2025-11-10 10:52:31.274702+0100 0x28dbee   Default     0x0                  133    0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] [LimitedLoadRequestHandler] Resolved request: 
directLoadPlatformExtensions: []
followupRequest: 
paths: [],
identifiers: ["io.macfuse.filesystems.macfuse.23"],
personalityNames: [],
extraRepositories: [],
dependencyKextsAndRepositories: [],
flags: [disallowAuth, clientPrivileged, ]
2025-11-10 10:52:31.274725+0100 0x28dbee   Default     0x0                  133    0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] [LimitedLoadRequestHandler] Serviced request: requestCompleted: false
followupRequest: 
paths: [],
identifiers: ["io.macfuse.filesystems.macfuse.23"],
personalityNames: [],
extraRepositories: [],
dependencyKextsAndRepositories: [],
flags: [disallowAuth, clientPrivileged, ]
2025-11-10 10:52:31.276739+0100 0x28d841   Default     0x0                  78495  0    kernelmanager_helper: Handling loadOrRebuildRequest: 
paths: [],
identifiers: ["io.macfuse.filesystems.macfuse.23"],
personalityNames: [],
extraRepositories: [],
dependencyKextsAndRepositories: [],
flags: [disallowAuth, clientPrivileged, ]
2025-11-10 10:52:31.276763+0100 0x28d841   Default     0x0                  78495  0    kernelmanager_helper: [FullLoadOrRebuildRequestHandler] Request: <private>
2025-11-10 10:52:31.276773+0100 0x28d841   Default     0x0                  78495  0    kernelmanager_helper: loading existing auxiliary collection contents from stashed instructions
2025-11-10 10:52:31.288224+0100 0x28d841   Activity    0x7234c4             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:52:31.288795+0100 0x28d841   Activity    0x7234c5             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:52:31.288919+0100 0x28d841   Activity    0x7234c6             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:52:31.290637+0100 0x28d841   Activity    0x7234c7             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:52:31.291511+0100 0x28d841   Activity    0x7234c8             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:52:31.297014+0100 0x28d841   Activity    0x7234c9             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:52:31.297148+0100 0x28d841   Activity    0x7234ca             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:52:31.297240+0100 0x28d841   Activity    0x7234cb             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:52:31.298175+0100 0x28d841   Activity    0x7234cc             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:52:31.298609+0100 0x28d841   Activity    0x7234cd             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:52:31.305006+0100 0x28d841   Activity    0x7234ce             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:52:31.305140+0100 0x28d841   Activity    0x7234cf             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:52:31.305226+0100 0x28d841   Activity    0x726280             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:52:31.306170+0100 0x28d841   Activity    0x726281             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:52:31.306628+0100 0x28d841   Activity    0x726282             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:52:31.310361+0100 0x28d841   Default     0x0                  78495  0    kernelmanager_helper: Validating extension at <private>
2025-11-10 10:52:31.318809+0100 0x28d841   Activity    0x726283             78495  0    kernelmanager_helper: (Security) SecKeyVerifySignature
2025-11-10 10:52:31.318977+0100 0x28d841   Activity    0x726284             78495  0    kernelmanager_helper: (Security) SecTrustEvaluateIfNecessary
2025-11-10 10:52:31.322888+0100 0x28d841   Default     0x0                  78495  0    kernelmanager_helper: Validating extension at <private>
2025-11-10 10:52:31.324450+0100 0x28d841   Default     0x0                  78495  0    kernelmanager_helper: [com.apple.kernelmanagerd.logging:LoadRequestResolution] checking bundle path /Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext for Kext io.macfuse.filesystems.macfuse.23 v5.1.1 in executable kext bundle io.macfuse.filesystems.macfuse.23 at /Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext
2025-11-10 10:52:31.324482+0100 0x28d841   Default     0x0                  78495  0    kernelmanager_helper: [com.apple.kernelmanagerd.logging:LoadRequestResolution] checking unstaged bundle path /Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext for Kext io.macfuse.filesystems.macfuse.23 v5.1.1 in executable kext bundle io.macfuse.filesystems.macfuse.23 at /Library/StagedExtensions/Library/Filesystems/macfuse.fs/Contents/Extensions/14/macfuse.kext
2025-11-10 10:52:31.324577+0100 0x28d841   Default     0x0                  78495  0    kernelmanager_helper: [com.apple.kernelmanagerd.logging:LoadRequestResolution] checking bundle path /Library/Apple/System/Library/Extensions/AppleMobileDevice.kext for Kext com.apple.driver.AppleMobileDevice v4.0 in codeless kext bundle com.apple.driver.AppleMobileDevice at /Library/Apple/System/Library/Extensions/AppleMobileDevice.kext
2025-11-10 10:52:31.324677+0100 0x28d841   Default     0x0                  78495  0    kernelmanager_helper: [com.apple.kernelmanagerd.logging:LoadRequestResolution] checking unstaged bundle path /Library/Apple/System/Library/Extensions/AppleMobileDevice.kext for Kext com.apple.driver.AppleMobileDevice v4.0 in codeless kext bundle com.apple.driver.AppleMobileDevice at /Library/Apple/System/Library/Extensions/AppleMobileDevice.kext


> 
> > Output of systemextensionsctl list is :
> > ---> 0 extension(s)
> 
> This command lists only certain system extensions, not kernel extensions. This means it's not relevant for macFUSE.
> 
> Just to make sure, are you booting from an external volume or are you trying to use macFUSE in a virtual machine? Both use cases are not supported by macOS. It's not a macFUSE limitation.

**I am booting from the internal disk, without using a virtual maching**

**Comment by bfleischer** [comment]
I don't know what this `com.apple.driver.AppleKIS` kernel extension is used for. There seems to be very little information available about it online, but an Apple kernel extension missing on your Mac sounds odd. It looks like the missing kernel extension is preventing the auxiliary kext collection from being built which prevents the macFUSE kernel extension from being loaded.

You could try running the following commands:

```
sudo kmutil clear-staging
```

And then start in Recovery Mode and run:

```
kmutil trigger-panic-medic --volume-root "/Volumes/Macintosh HD"
```

This will disable all third-party kernel extensions and reset staging. Then try to go through the approval process for the macFUSE kernel extension again.

**Comment by Franck177** [comment]
Problem not yet solved despite following actions : 

**1/ reinstallation of MacOs Sequoia** 
>    -> KO approval of  Macfuse kernel extension still not working (demand of reapproval of Macfuse after the restart)

**2/ uninstallation of Macfuse (with uninstaller from  https://macfuse.io)  +  reinstallation of MacOs Sequoia + resinstallation of MacFuse** 

>       -> KO approval of  Macfuse kernel extension still not working (demand of reapproval of Macfuse after the restart)

**3/ reinstallation of MacOs Sequoia** 
>.      -> OK, effective  
    
4/ disable all third-party kernel extensions and reset staging
> + kmutil clear-staging (-> effective) 
>     + kmutil trigger-panic-medic in recovery mode (->effective) 
>     +  restart of Mac OS in normal mode 
>     -> systems and app well running after the following warning saying that if you try to use an app needing an extension, you will be asked to demand its approval

<img width="306" height="316" alt="Image" src="https://github.com/user-attachments/assets/ee955bd2-53f2-40da-b227-c224227d3505" />
 
>  ->  kernel manager log 
[2025-11-14 18.16.08 Kernel Manager Log.rtf](https://github.com/user-attachments/files/23563114/2025-11-14.18.16.08.Kernel.Manager.Log.rtf)

**5/ install of Macfuse (from  https://macfuse.io) and demand of approval of Macfuse kernel extension**
     

> -> KO : two errors message at the restart : one warning that the system has been rebooted due to a problem and the other asking to approve kernel extension

<img width="609" height="337" alt="Image" src="https://github.com/user-attachments/assets/110f86d4-1f78-44b9-8070-fcb9bdfcc942" />
    

> -> approval requested : MacFuse extension + an apple extension (apple extension whose approval was  not required since the uninstallation of Macfuse two days before) 

<img width="833" height="496" alt="Image" src="https://github.com/user-attachments/assets/8a6d444b-1968-4326-b33c-9eae7461808f" />

-> System report

[2025-11-14 à 18.29.15 System error report coming at the first boot after approval of Macfuse extension .rtf](https://github.com/user-attachments/files/23563128/2025-11-14.a.18.29.15.System.error.report.coming.at.the.first.boot.after.approval.of.Macfuse.extension.rtf)

->  kernel manager log 

[2025-11-14 18.24.xx Kernel Manager Log .rtf](https://github.com/user-attachments/files/23563119/2025-11-14.18.24.xx.Kernel.Manager.Log.rtf)

**Comment by bfleischer** [comment]
The logs you provided show several outdated kernel extensions on your Mac (such as Soundflower) that appear to have been migrated from an older Intel-based system. Reinstalling macOS didn’t resolve the issue because the SSD wasn’t formatted beforehand, so all of those incompatible extensions remained in place.

There are documented cases where legacy or unsupported kernel extensions prevent the Auxiliary Kext Collection from being built, which in turn stops compatible extensions—like macFUSE—from loading. This behavior isn’t a bug in macFUSE but rather a result of the current environment on your Mac.

I recommend removing all of the legacy or unsupported kernel extensions listed in your log. A more thorough approach would be to format your SSD and then reinstall macOS. This will eliminate all of the leftover clutter—but it will also erase your data. Only consider this option if you have reliable backups and are confident in restoring your system afterward.

**Comment by Franck177** [comment]
Thanks to Benjamin recommandation and after a time consuming diagnostic, the issue is fixed.
Nothing to do with MacFuse.

The trigger was the upgrade of MacOS.
The  root cause of the issue was corrupted data somewhere in the user data external SSD connected with the MAC

The trigger  is strange : the system is installed on an internal SSD and upgrade process is not supposed to use the external SSD. 
The root cause is strange : this external SSD had never been used as a SSD system one and is supposed to only contain user data. Question of how this SSD could had been corrupted is pending.

What is not sufficient to fix : Formatting the internal SSD and then installing Sequoia and Tahoe on the internal SSD but WITH THE SSD CONNECTED WITH THE MAC  was not sufficient to fix the issue : kernel extensions were still corrupted.
How to fix : Erasing the internal SSD and installing MacOS w/o the external SSD connected has resolved the issue.


By the Way about MacOS Sequoia and Tahoe  native extensions : installation of MACOS on the SSD of  a new M4 computer or on an erased SSD of an old M1 one, bring some errors in the kernel management : for some reasons MacOS try to install HighPointRR.kext and HighPointIOP.kext despite the fact that those binary are for X86_64 and  try to load Extension with identifier 'com.apple.driver.kis.AppleKIS' despite the fact that it could not find it.

Thank you for having supported me.

**Comment by bfleischer** [comment]
I'm glad you found a solution. Thanks for posting your findings.
