### ISSUE TITLE
Trash can't be enabled in macOS Sierra and High Sierra using loopbackFS

### ISSUE THREAD

**Issue by pmalhaire** [osxfuse/osxfuse#424]
This is not properly an osxfuse issue I guess it's a behavior change in macOS. 
Hopefully, I just missed something in configuring the volume and I'll had that to the FAQ.

From my past experience the following did enable the thrash in the osxfuse volume.

```bash
mkdir .Trashes
chmod 0333 .Trashes
chown root:wheel .Thrashes
```

Restart the Finder

I tried this using the loopbackfs and it did not work. 

### Things I tried : 

- using `user:staff` instead of `root:wheel` since it's the owner of the Trash.
- using `.Trash` instead of `.Trashes`

Any help would be great !

**Comment by louismartin** [comment]
Same problem with EncFS that uses osxfuse, any news on this?

**Comment by lightning-zgc** [comment]
I meet this problem too! After some experiments, I found a possible way. I'm not sure this is a bug in OXSFUSE or something else. I tested this on gocryptfs and it worked.
```bash
chmod 700 .Trashes  
mkdir .Trashes/$UID
```
---
More info:
When the `.Trashes` folder is empty while deleting files, the finder will set the attr of the `.Trashes` folder to `d-wx-wx-wt`. This would make the `.Trashes` unreadable and further cause the Trash function to be unavailable.
However, after we create the User folder `$UID` in `.Trashes`, finder will enable Trash function without reset the attr.

**Comment by doits** [comment]
Thanks for https://github.com/osxfuse/osxfuse/issues/424#issuecomment-554926401, I could enable Trash with this, too. One remark though: This has to be present when the filesystem is mounted already. So to make it work:

- mount the filesystem
- `mkdir .Trashes`
- `chmod 700 .Trashes`
- `mkdir .Trashes/$UID`
- unmount the filesystem
- mount it again

trash should work now!

**Comment by pmalhaire** [comment]
great look like fixed

**Comment by eugenesvk** [comment]
Missed when this was closed as fixed, but just tested now following the steps above, checked the permissions, remounted/restarted, and it still doesn't work on the same gocryptfs volume.
Is there something more to it?
I see there is this https://github.com/osxfuse/osxfuse/wiki/Mount-options#local with a comment that seems relevant

>  (a .Trashes. directory will be created, for one). 

but then it's marked as experimental, so a bit worried re. using it for an encrypted volume...

upd: it turns out you don't need to mess with any permissions and UIDs, you can just create a `.Trashes` folder with the default `755`, then the `local` flag does everything else — the system automatically creates UID a subfolder with `700` permission
