### ISSUE TITLE
On macOS 10.14.x, update throws a 32-bit warning on "ksurl"

### ISSUE THREAD

**Issue by alanhoyle** [osxfuse/osxfuse#592]
I just updated from FUSE 3.8.x to 3.9 via the FUSE Control Panel, and when I clicked the "Update" button, it popped up a window complaining that "ksurl" needed to be updated or it would stop working on future versions of macOS. I've seen a similar pop-up for other apps that have small 32-bit pieces.  

If this hasn't been updated in 3.9, it really should be pretty soon, as it will stop working in macOS 10.15.

**Comment by bfleischer** [comment]
The issue is fixed in the new 3.9.1 release. Thanks for reporting it.

**Comment by alanhoyle** [comment]
Thank you!

**Comment by alanhoyle** [comment]
As an aside, I finally updated again  (from 3.9.0 to 3.9.2) and I can confirm that the issue did not crop up this time.  Thanks again!

**Comment by mixtly87** [comment]
@bfleischer  @alanhoyle 
My users still see this message without exception even when updating to latest osxfuse 3.9.2.
The way they update fuse is usually via autoinstall script instead of PreferencePane, but some also use FUSE PreferencePane to update to latest version.

Did anyone notice similar behavior?

**Comment by bfleischer** [comment]
The issue is fixed in version 3.9.1. This means that users will not see the warning when updating from a version greater or equal to 3.9.1 to a newer version, e.g. 3.10.0.

Are you sure your users were already on 3.9.1 when updating to 3.9.2?
