### ISSUE TITLE
macOS 11.5 - The system extension required for mounting macFUSE volumes could not be loaded.

### ISSUE THREAD

**Issue by Thireus** [osxfuse/osxfuse#828]
On macOS 11.5, the v4.1.2 extension cannot be loaded, even when the extension is allowed.

The following message is displayed no matter what:
```
System Extension Blocked

The system extension required for mounting macFUSE volumes could not be loaded.

Please open the Security & Privacy System Preferences pane, go to the General preferences and allow loading system software from developer "Benjamin Fleischer". A restart might be required before the system extension can be loaded.

Then try mounting the volume again.
```

**Comment by bfleischer** [comment]
Did you restart your Mac?

**Comment by Thireus** [comment]
Yes. It was already installed on 11.4. I've upgraded to 11.5 and the kext won't load. I tried to reinstall & restart, still won't load.

4.2.0 works fine though.

**Comment by titver968** [comment]
I have the same problem.

**Comment by bfleischer** [comment]
@titver968 Which version of macFUSE are you using? Did you try updating to 4.2.0?

**Comment by titver968** [comment]
I use the stable Version 4.1.2. I will try the 4.2 now.

**Comment by titver968** [comment]
Th, it’s works with 4.2.0

Best regards
Titus

Am 23.07.2021 um 09:53 schrieb Benjamin Fleischer ***@***.******@***.***>>:



@titver968<https://github.com/titver968> Which version of maFUSE are you using? Did you try updating to 4.2.0?

**Comment by FGasper** [comment]
I’ve had the same problem with 10.14.5 -> 10.14.6, but 4.2.0 does *not* fix the problem for me.

**Comment by artmg** [comment]
Thanks @FGasper you were right to raise your problem as separate issue #829 because you DON'T have the same problem - the title of this issue clearly states **macOS 11.5**, and so far everyone reporting the issue with that os version says that it was **fixed** by moving to macFUSE 4.2.0

**Comment by neurodroid** [comment]
This issue was fixed for me in Big Sur up to 11.5.1 by macFUSE version 4.2.0.
But now it just re-appeared when I upgraded to Big Sur 11.5.2 - no entry in the developers section any longer even after a re-install of 4.2.0.

**Comment by neurodroid** [comment]
> This issue was fixed for me in Big Sur up to 11.5.1 by macFUSE version 4.2.0.
> But now it just re-appeared when I upgraded to Big Sur 11.5.2 - no entry in the developers section any longer even after a re-install of 4.2.0.

After a system reboot, macFUSE 4.2.0 is now simply working without any complaints on Big Sur 11.5.2. There's still no entry in the approved developers section though.

**Comment by katzlbt** [comment]
Even macFUSE 4.1.2 works on Big Sur 11.5.2 after a simple system reboot after the upgrade (for me). No need to install a new version. The extra reboot does the trick.

**Comment by artmg** [comment]
Likewise. The first time I attempt to mount a volume after upgrading to macOS 11.5.2, the error appears, but there is **no** need to allow anything in Security & Privacy Preferences, it simply needs a reboot. Slightly annoying to have a couple of extra steps after upgrade:

* attempt a macFUSE mount, 
* dismiss the error, 
* restart macOS

but as long as you know and expect this, it's pretty quick to overcome :)

**Comment by Thireus** [comment]
Thanks for the tip @artmg, I upgraded to 11.5.2 as well and rebooting the machine after the message appears solves it.

**Comment by FFroehlich** [comment]
I am on 11.5.2 and have reinstalled osxfuse 4.2.0 and rebootet multiple times but the error message is not going away.

**Comment by artmg** [comment]
@FFroehlich please describe the steps you take, one by one, and write out any error message you receive, all in the order it happens. That will help others diagnose your issue. Thanks

**Comment by FFroehlich** [comment]
> @FFroehlich please describe the steps you take, one by one, and write out any error message you receive, all in the order it happens. That will help others diagnose your issue. Thanks

1) install macFUSE 4.2.0 via the system preferences pane (checking show beta versions to not install 4.1.2) – I also tried installing by downloading installer from webpage
2) reboot
3) call sshfs via command line
4) receive the error message mentioned above (also attached)

<img width="261" alt="image" src="https://user-images.githubusercontent.com/14923969/131705116-068705f0-2424-4fe1-b376-7a57819f72bd.png">

5) after pressing either button, I get the following error on the command line and sshfs terminates:

`mount_macfuse: the file system is not available (1)`

**Comment by artmg** [comment]
Ok, thanks @FFroehlich, so if you

5. Press Cancel and disregard the error
6. reboot macOS
7. call SSHFS via the command line

Do you still get the same "System Extension Blocked" error? 

The important thing about the reboot is it should be **after you try to use macFUSE** not just after you have installed it. Get the error - reboot - try and hopefully it should work.

**Comment by FFroehlich** [comment]
> Ok, thanks @FFroehlich, so if you
> 
> 1. Press Cancel and disregard the error
> 2. reboot macOS
> 3. call SSHFS via the command line
> 
> Do you still get the same "System Extension Blocked" error?

Yes, the error persist after another reboot.

**Comment by artmg** [comment]
How unfortunate. Everyone else in this thread using macFUSE 4.2.0 on macOS 11.5 seems to find the reboot fixes their issue, so we need to find out what is different in your case. 

Although no-one here says they are using sshfs, recent comments in issue #705 say that sshfs users got things working with 4.2.0 on Big Sur. Are there any side issues mentioned in there that might apply to you?

Is your mac managed by a company who might have locked something down?

Have you checked in https://github.com/osxfuse/sshfs/issues/ to see if your problem is mentioned there? Or if it's related to the specific command-line that you are calling in sshfs? If this issue only occurs with sshfs, perhaps it might be better to raise it there instead?

**Comment by FFroehlich** [comment]
> How unfortunate. Everyone else in this thread using macFUSE 4.2.0 on macOS 11.5 seems to find the reboot fixes their issue, so we need to find out what is different in your case.
> 
> Although no-one here says they are using sshfs, recent comments in issue #705 say that sshfs users got things working with 4.2.0 on Big Sur. Are there any side issues mentioned in there that might apply to you?
> 
> Is your mac managed by a company who might have locked something down?
> 
> Have you checked in https://github.com/osxfuse/sshfs/issues/ to see if your problem is mentioned there? Or if it's related to the specific command-line that you are calling in sshfs? If this issue only occurs with sshfs, perhaps it might be better to raise it there instead?

I tried running `/Library/Filesystems/macfuse.fs/Contents/Resources/load_macfuse; echo $?`, which returns 1, indicating that the macfuse cannot be loaded, which makes me believe the issue is not related to sshfs. Is there a better way to test macfuse independent of sshfs?

**Comment by artmg** [comment]
I cannot find any documentation on how you could diagnose why `load_macfuse` is failing ... perhaps the developer @bfleischer may be able to help?

**Comment by Demannu** [comment]
I can add to the list of users on macOS 11.5.2 in which macFUSE 4.2.0 does not load. It presents the System Preferences window but the steps described above did not work
- Dismiss notification
- Reboot
- Attempt to mount again
It also doesn't at any point show Ben's name for approval, if you hit approve it just asks to restart and starts the process over again

**Comment by imraan1901** [comment]
What I did to get macFUSE to work was to
1) Uninstall macFUSE
2) Disable System Integrity Protection https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection
3) While System Integrity Protection is disabled, install macFUSE
4) Do a restart without enabling System Integrity Protection and load/approve the macFUSE Extension in the Security Pane
4) Enable System Integrity Protection

**Comment by shera-amit** [comment]
> > Ok, thanks @FFroehlich, so if you
> > 
> > 1. Press Cancel and disregard the error
> > 2. reboot macOS
> > 3. call SSHFS via the command line
> > 
> > Do you still get the same "System Extension Blocked" error?
> 
> Yes, the error persist after another reboot.

I have the same issue. It persists even after reboot.

**Comment by artmg** [comment]
_**Update December 2024** 
I compiled this list of instructions back in September 2021 in order to help people trying to make sense of this thread in the absence of other documentation. I have [now been informed](https://github.com/macfuse/macfuse/issues/828#issuecomment-2502486206) that step 9 should not be followed. However, come to think of it, all the software in this stack has evolved so much that no-one should really be following 40 month old instructions anyhow._

So the prevailing instructions coming from this thread seem to be:

1. Install latest macFUSE (>=4.2.0)
2. restart macOS
3. attempt to mount your filesystem (using whatever software you have that relies on macFUSE)

- IF you get the error "System Extension Blocked" 

4. Cancel the error dialog
5. restart macOS
6. attempt once more to mount your filesystem

- IF you STILL get the error "System Extension Blocked" 

7. Cancel the error dialog
8. uninstall macFUSE

_Update Dec 2024: disabling SIP is not recommended_
9. ~disable System Integrity Protection~ - https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection

10. restart macOS (as part of that process)
11. install macFUSE (~while System Integrity Protection is disabled~)
12. restart macOS (without enabling System Integrity Protection)
13. attempt once more to mount your filesystem, and you will _not_ be surprised to get the error "System Extension Blocked" 
14. **this time** open System Preferences / Security and Approve the macFUSE Extension
15. Enable System Integrity Protection
16. reboot your macOS
17. you should now be able to mount your filesystem without error (but perhaps **with** a little dance of joy?)

If you are highly pessimistic you _could_ skip straight to step 8, but only a small (but significant) number of cases seem to need such extreme measures, so try the first steps first.

**Comment by gamvrosi** [comment]
FYI, for anyone having the same issue with macOS 11.6, @artmg's approach still works.

**Comment by Clovenhoofblues** [comment]
Not sure if the issue somehow relates to "managed devices" but I had the same issue; there was a prompt to approve but no "button" in Security Prefs.
We use Jamf so I added a config with allowed system/kernel extensions of ID 3T5GSNBU6W (no need to add io.macfuse.filesystems.macfuse) and it works now without going for the @artmg solution.
(ID based on; codesign -dv /Library/Filesystems/macfuse.fs/Contents/Extensions/12/macfuse.kext)

**Comment by artmg** [comment]
That's really useful, @Clovenhoofblues , seeing the ID (and how to get it), as that could be relevant to any organisation using an Apple MDM vendor solution to lock down its endpoints, whether it's Jamf, Kandji, JumpCloud, IBM, Hexnode, or one of the many others. Thanks

**Comment by bfleischer** [comment]
Disabling System Integrity Protection should not be required to use macFUSE. If you can't make it work without disabling System Integrity Protection, you should raise the issue with Apple. All macFUSE releases are signed and notarized and I test every new release. They all load fine for me without disabling System Integrity Protection.

**Comment by DanielRonnstam** [comment]
I have done all you tell above, I'm on Big Sur 11.6, Installed MacFUSE 4.2.0, SSHFS 2.5.0 with disabled SIP and I have approved the extension and rebooted a lot of times. But, when I enter the blow in Terminal the folder to mount server stuff into, disappears. When I reboot, it's back again but with no content. I have tested the login credentials in FileZilla and they work.

Anyone else having the same issue? Solution? Is the syntax below correct?

sudo sshfs -o reconnect,IdentityFile=/Users/dannes/Documents/ORACLE_server/foundry.key [my_usernamn]@[my_server]:/home/ubuntu/foundryuserdata/ /Users/dannes/Documents/FoundryHDD

**Comment by DanielRonnstam** [comment]
Then when I try to enter the command again, I get this message;

mount_macfuse: mount point /Users/dannes/Documents/FoundryHDD is itself on a macFUSE volume

**Comment by DanielRonnstam** [comment]
I searched and found that the folder exists but has changed some permissions or something. Now it looks like this when I try to get info, and say in the bottom that "You have unknown access"

![image](https://user-images.githubusercontent.com/48160813/135255463-c2797ee2-d2a9-44bd-b926-d84c1c1fe7a8.png)

**Comment by bfleischer** [comment]
@DanielRonnstam Don't use `sudo` when calling sshfs and look into the `defer_permisions` (https://github.com/osxfuse/osxfuse/wiki/Mount-options#default_permissions-and-defer_permissions) option. Please post questions like this on our Google group (https://groups.google.com/g/osxfuse-group).

**Comment by emmajarv** [comment]
> So the prevailing instructions coming from this thread seem to be:
> 
> 1. Install latest macFUSE (>=4.2.0)
> 2. restart macOS
> 3. attempt to mount your filesystem (using whatever software you have that relies on macFUSE)
> 
> * IF you get the error "System Extension Blocked"
> 
> 1. Cancel the error dialog
> 2. restart macOS
> 3. attempt once more to mount your filesystem
> 
> * IF you STILL get the error "System Extension Blocked"
> 
> 1. Cancel the error dialog
> 2. uninstall macFUSE
> 3. disable System Integrity Protection - https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection
> 4. restart macOS (as part of that process)
> 5. install macFUSE (while System Integrity Protection is disabled)
> 6. restart macOS (without enabling System Integrity Protection)
> 7. attempt once more to mount your filesystem, and you will _not_ be surprised to get the error "System Extension Blocked"
> 8. **this time** open System Preferences / Security and Approve the macFUSE Extension
> 9. Enable System Integrity Protection
> 10. reboot your macOS
> 11. you should now be able to mount your filesystem without error (but perhaps **with** a little dance of joy?)
> 
> If you are highly pessimistic you _could_ skip straight to step 8, but only a small (but significant) number of cases seem to need such extreme measures, so try the first steps first.

I have the same issue that macFUSE is not working after several re-boot attempts. I got it working through these instruction but when I enable System Integrity Protection, the same problem persists. Is there anything else I could do as I don't want to permanently disable SIP?

**Comment by gmuth** [comment]
Have you tried [deleting /private/var/db/KernelExtensionManagement in recovery mode](https://github.com/osxfuse/osxfuse/issues/783)?
This should allow creating fresh kext settings as required by the current version of macfuse and macos.

**Comment by emmajarv** [comment]
> Have you tried [deleting /private/var/db/KernelExtensionManagement in recovery mode](https://github.com/osxfuse/osxfuse/issues/783)?
> This should allow creating fresh kext settings as required by the current version of macfuse and macos.

@gmuth Thanks for the help! Unfortunately, after I uninstalled macFUSE, deleted this folder and reinstalled macFUSE, the problem is still there.

In my working group, we have three Macs with same version of Big Sur but only mine shows this problem. I'm running out of ideas.

**Comment by FFroehlich** [comment]
I am also unable to get macFUSE to work while SIP is enabled. Following the guide described above, I was able to click the "allow" button in systems preferences after disabling SIP. Following a reboot, macFUSE works and I can mount drives via sshfs. However, macFUSE/sshfs stop working as soon as I re-enable SIP.

**Comment by gmuth** [comment]
To verify that the kext is enabled run:

```
sudo sqlite3 /private/var/db/SystemPolicyConfiguration/KextPolicy "select * from kext_policy where team_id='3T5GSNBU6W';"
```

My output is: (team_id,bundle_id,allowed,developer_name,flags)

```

3T5GSNBU6W|com.github.osxfuse.filesystems.osxfuse|1|Benjamin Fleischer|12
3T5GSNBU6W|io.macfuse.filesystems.macfuse|1|Benjamin Fleischer|1
```

What is your output?
1 in column 3 means "allowed"
flags in column 5 should be 12 (bits 8+4, where can I find a description of the flag bits?)

@bfleischer, does your kext use two bundle-ids? If you use only one I assume "io.macfuse" is the latest.

(Rebuilding the kextpolicy db is described here: https://developer.apple.com/forums/thread/100079)

**Comment by emmajarv** [comment]
> To verify that the kext is enabled run:
> 
> ```
> sudo sqlite3 /private/var/db/SystemPolicyConfiguration/KextPolicy "select * from kext_policy where team_id='3T5GSNBU6W';"
> ```
> 
> My output is: (team_id,bundle_id,allowed,developer_name,flags)
> 
> ```
> 
> 3T5GSNBU6W|com.github.osxfuse.filesystems.osxfuse|1|Benjamin Fleischer|12
> 3T5GSNBU6W|io.macfuse.filesystems.macfuse|1|Benjamin Fleischer|1
> ```
> 
> What is your output? 1 in column 3 means "allowed" flags in column 5 should be 12 (bits 8+4, where can I find a description of the flag bits?)
> 
> @bfleischer, does your kext use two bundle-ids? If you use only one I assume "io.macfuse" is the latest.
> 
> (Rebuilding the kextpolicy db is described here: https://developer.apple.com/forums/thread/100079)

Here's my output
`3T5GSNBU6W|com.github.osxfuse.filesystems.osxfuse|1|Benjamin Fleischer|5
3T5GSNBU6W|io.macfuse.filesystems.macfuse|1|Benjamin Fleischer|1`

**Comment by gmuth** [comment]
You could try to update via sql the flags-value to 12 or remove both entries to trigger the allow-dialog.
Could you please have your coworkers run the command and provide their output as well?
If their output is different as well we probably have the cause and can fix it.

**Comment by bfleischer** [comment]
> @bfleischer, does your kext use two bundle-ids? If you use only one I assume "io.macfuse" is the latest.

Since version 4.0 the bundle identifier starts with `io.macfuse`. In older releases it starts with `com.github.osxfuse`.

**Comment by fridary** [comment]
For me nothing above helped, because of using M1 chip, but rebooting Mac with changing security settings on the startup disk solved problem https://support.apple.com/guide/mac-help/change-security-settings-startup-disk-a-mac-mchl768f7291/mac

**Comment by BradKollmyer** [comment]
> For me nothing above helped, because of using M1 chip, but rebooting Mac with changing security settings on the startup disk solved problem https://support.apple.com/guide/mac-help/change-security-settings-startup-disk-a-mac-mchl768f7291/mac

I can confirm the same thing fixed the issue on my M1 Mac. I got it set on an Intel Mac and did not have to do this step.

**Comment by wookayin** [comment]
@BradKollmyer @fridary Did you use Reduced Security - Allow user management of kernel extensions from identified developers? I am still stuck (on a M1 mac) with the error 'System Extension Blocked' and 'New system extensions require a restart before they can b eused' for numberless of reboots.

**Comment by gmuth** [comment]
With my M1 (2021) the procedure to allow the new system extension indeed needed a reboot. however I did not have to disable system security but merely just allow the new extension and than reboot.

**Comment by jdmarlow0** [comment]
I’m on Big Sur 11.5.2 with Intel Mac Mini struggling with this same exact issue with MacFUSE.  It works when SIP is disabled but as soon as SIP is reenabled it stops working and I am required to allow the extension again.  I get stuck in loops of allowing, rebooting, allowing, rebooting.  It never sticks.  I’m leaving SIP disabled so that I can work but would love to know another way if it exists.

**Comment by joshcarter06** [comment]
I tried to install 4.2.4 on a brand new MacBook Pro (Monterey 12.0.1, Apple M1 Max) and I got the same System Extension Blocked error. I was prompted to reduce the security settings in Recovery Mode, but I declined.

**Comment by jdmarlow0** [comment]
> I tried to install 4.2.4 on a brand new MacBook Pro (Monterey 12.0.1, Apple M1 Max) and I got the same System Extension Blocked error. I was prompted to reduce the security settings in Recovery Mode, but I declined.

My experience so far has been that you cannot successfully install and use MacFUSE on Big Sur and later without disabling SIP and keeping it disabled permanently.  I wish there was another way around this but I have not come across one.

**Comment by joshcarter06** [comment]
> > I tried to install 4.2.4 on a brand new MacBook Pro (Monterey 12.0.1, Apple M1 Max) and I got the same System Extension Blocked error. I was prompted to reduce the security settings in Recovery Mode, but I declined.
> 
> My experience so far has been that you cannot successfully install and use MacFUSE on Big Sur and later without disabling SIP and keeping it disabled permanently. I wish there was another way around this but I have not come across one.

Yikes. I'm trying to use macFUSE to install VeraCrypt to make some files even more secure, so I'm not willing to disable SIP. Thanks for the update @jdmarlow0

**Comment by bfleischer** [comment]
@jdmarlow0 Disabling System Integrity Protection is **NOT** required to use macFUSE. Please stop spreading false information. Earlier releases of macOS 11 contained several bugs that prevented third-party kernel extensions from loading. Apple addressed many of these issues in 11.3. All macFUSE releases are signed and notarized. I test every release and they all load fine for me on M1 and Intel Macs with System Integrity Protection **ENABLED**. If it does not work for you, it's most likely an issue on your Mac. If you can, do a clean install of macOS and then try loading macFUSE. It should work just fine. Disabling System Integrity Protection simply masks some issues on your Mac that might prevent macFUSE from loading. 

@joshcarter06 On M1 Macs you need to allow loading third party kernel extensions in recovery mode first, before macFUSE can be loaded. There is no other way to use third-party file systems without "lowering" security settings in recover mode because Apple does not provide a non-kernel API for developing full-featured file systems. If there was such a non-kernel API, I would update macFUSE to use it instead of the old kernel API, but there is none and my hands are tied.

**Comment by jdmarlow0** [comment]
@bfleischer thanks for confirming that MacFUSE does work with SIP enabled.  I’m just reporting anecdotal evidence from my Mac.  It could be something specific to my system but I cannot afford to do a fresh OS install to test that theory.

**Comment by joshcarter06** [comment]
@bfleischer Thank you for the clarification! I understand Apple's walled garden. Enabling 3rd Party extensions is a big difference from disabling SIP. Thanks for your good work!

**Comment by cdevers-es** [comment]
Hi, @bfleischer —

> I test every release and they all load fine for me on M1 and Intel Macs with System Integrity Protection ENABLED. If it does not work for you, it's most likely an issue on your Mac. If you can, do a clean install of macOS and then try loading macFUSE.

We’re getting some reports that the FUSE software (v4.2.3) is not installing & loading properly on macOS 11.6.2 Big Sur, on Intel Macs that had apparently been working fine with 11.6.0, and inconsistent reports as to whether turning SIP off is helping. (Turning off SIP is of course the wrong approach, but as a short-term workaround, it has been considered, but apparently turning it off may or may not help anyway.)

Given that the problem appears to affect multiple computers, reinstalling all of them doesn’t seem practical, though we could maybe suggest trying this on a test basis. (I’ve also considered suggesting an upgrade to macOS 12 Monterey, but we're anticipating pushback on that line of thought.)

When you write “it’s most likely an issue on your Mac”, it would help to have a sense of what sorts of “issues” we should be looking for, but I realize that's an annoyingly open-ended question. We’re still investigating. 

Can you at least confirm that in your dev/test work, you have tried out macOS 11.6.2, and found MacFUSE to work on that Big Sur version for you?

Thanks!

**Comment by gmuth** [comment]
Hi all,
When I ran into the same issue (though on another system version of macos) I found varies answers which did not sound logic to me. The difficult part of this issue is: How can someone reproduce it?

* hypothesis:

1. Fresh installs
Installing macfuse works fine when FIRST installed on any(?) compatible version of macOS.

2. Update installs
When upgrading macOS it is likely that you also upgrade macfuse.
This is what does NOT work for some users. But what exactly is the issue?
In my case I found that the bundle-id has changed from com.github.osxfuse.filesystems.osxfuse to io.macfuse.filesystems.macfuse. Also the allowed flags have changed. (just an observation - not a confirmed issue yet)

3. open question
what are the meanings of the "sip allowed flags" in kext_policy?
what (existing?) values are checked by macos that trigger the "sip config process"?

* SIP config

It's all related to the SIP config. So I can see a lot of time consuming things to look into.

- hypothesis

there's a bug in macOS that does not migrate existing sip permissions correct under certain conditions.
I assume this bug is present in all macOS versions that use SIP

* action proposals

A. make sure no permissions need to be migrated

@bfleischer, Is there a uninstall procedure available that does remove the existing sip permissions?
If yes - you could document "before updating macOS I recommend to uninstall macos fuse first"

B. remove old sip permissions and let the macfuse-install-process ask and set the permissions from scratch.

open question: how can we achieve that?

idea:
"sqllite" remove the entry from /private/var/db/SystemPolicyConfiguration/KextPolicy
rebuild the protection cache as documented here https://developer.apple.com/forums/thread/100079

**Comment by bfleischer** [comment]
> Given that the problem appears to affect multiple computers, reinstalling all of them doesn’t seem practical, though we could maybe suggest trying this on a test basis. (I’ve also considered suggesting an upgrade to macOS 12 Monterey, but we're anticipating pushback on that line of thought.)

I have never been able to reproduce these issues on any of my Macs. That being said, possible reasons on macOS 11 and macOS 12 are:

* `/var/db/SystemPolicyConfiguration/KextPolicy` is damaged
* `/var/db/SystemPolicyConfiguration/KextPolicy` has the wrong owner or mode
* `/var/db/SystemPolicyConfiguration/KextPolicy` is missing the restricted flag
* The kernel extension staging directory `/Library/StagedExtensions` is missing or has the wrong owner or mode
* macOS did copy the wrong version of the kernel extension to the staging directory. This can happen on macOS < 11.3 and is a bug in macOS.

The `/var/db/SystemPolicyConfiguration/KextPolicy` issues I have investigated were usually the result of the KextPolicy database being edited manually in the past. 

There are most definitely more possible causes for the issues you are seeing. But, I've never seen any of the reported issues on a clean install of macOS.

Disabling SIP masks some of the above issues but it is in no case a proper fix. macFUSE fulfills all the requirements for being loaded with SIP enabled (signed and notarized). macFUSE asks macOS to load the kernel extension and passes the path of the kernel extension to macOS. That's all macFUSE does. Then macOS takes over and handles the consent dialog, checks the code signature and notarization status, stages the extension, updates the Auxiliary Kernel Collection asks the user to reboot or to "lower" the security setting in recovery mode.

Apple did not document the kernel extension loading process. It's a big black box. This makes finding the sand in the gears hard. Checking the system logs (Console.app) might give you a clue what's causing the problem. Run `kmutil log stream` in Terminal before trying to load the kernel extension and check its output.   

> Can you at least confirm that in your dev/test work, you have tried out macOS 11.6.2, and found MacFUSE to work on that Big Sur version for you?

Yes, I've tested on 11.6.2 on an M1 Mac and I'm not seeing any issues.

**Comment by cdevers-es** [comment]
> I have never been able to reproduce these issues on any of my Macs. That being said, possible reasons on macOS 11 and macOS 12 are [… lots of stuff related to `/var/db/SystemPolicyConfiguration/KextPolicy` & `/Library/StagedExtensions` …]

Thank you! I have relayed this to our tech support team, and we’ll dig there on computers where the problem has been reproduced. 

We tried reproducing the problem on an in-house macOS 11.6.2 VM today, and could _not_ reproduce the problem, so we agree with you that it “should” work, and it’s a matter of identifying what’s different about the Macs that won't load the software at runtime. 
 
> […] Apple did not document the kernel extension loading process. It's a big black box. This makes finding the sand in the gears hard. Checking the system logs (Console.app) might give you a clue what's causing the problem. Run `kmutil log stream` in Terminal before trying to load the kernel extension and check its output.

I wasn’t aware of `kmutil`, so we’ll add that to our bag of tricks. We were planning to start with just `log show --last=1m` after reproducing the problem, to see if that generates a useful-enough trace of what happened. Sounds like adding the “KernelManagement Utility” to the mix should provide helpful information.

> Yes, I've tested on 11.6.2 on an M1 Mac and I'm not seeing any issues.

Okay, thanks. The reports we're getting appear to be with Intel Macs, but I’m not sure if the CPU architecture is relevant here.

**Comment by bfleischer** [comment]
> In my case I found that the bundle-id has changed from com.github.osxfuse.filesystems.osxfuse to io.macfuse.filesystems.macfuse. Also the allowed flags have changed. (just an observation - not a confirmed issue yet)

The bundle ID changed in version 4.0.0. But it is highly unlikely for this to cause kernel extension loading issues.

What do you mean by "the allowed flags changed"?

> @bfleischer, Is there a uninstall procedure available that does remove the existing sip permissions?
If yes - you could document "before updating macOS I recommend to uninstall macos fuse first"

What exactly do you mean by "sip permissions"? 

macOS handles user consent. The only way to reset this would be booting into the recovery environment and running unsafe commands in Terminal. This is definitely nothing a normal user can be asked to do. While there are some users who are running into kernel extension loading issues, the great majority of macFUSE users is not. So this is not a general issue.

Uninstalling macFUSE is easy. Simply run the uninstaller from the macFUSE disk image or use the uninstall button in the macFUSE preference pane. However, this does not reset user consent. There is no way to do this outside of the recovery environment. Uninstalling macFUSE will not help in case there is something wrong with the KextPolicy database and should not be necessary.

**Comment by nean-0** [comment]
I had this issue and I tried many of of the prop

**Comment by nean-0** [comment]
Just wanted to add how it was resolved for me.

I upgraded to Monterey from Catalina (10.15.7  -> 12.1) a week ago. I had this problem that macfuse wouldn't load even if I allowed it from the "Security and Privacy" dialog. I tried many of the proposals I found googling around, but no. In the end it got resolved after I had disabled SIP in recovery mode and then allowed it in the "Security and Privacy" dialog. And it still loads since after I have re-enabled SIP.

To compare against a clean install is not really a general use case. I don't think people constantly reinstall their computers from scratch (with all the associated work to get one's preferred environment up).

**Comment by bfleischer** [comment]
> To compare against a clean install is not really a general use case. I don't think people constantly reinstall their computers from scratch (with all the associated work to get one's preferred environment up).

While I agree that the great majority of users simply upgrade to newer versions of macOS, a clean install is the only clearly defined state I can use for comparison. The facts that there don't seem to be any issues on clean installs of macOS and macFUSE working just fine for the great majority of users who upgraded macOS, points to this not being a general issue. It would be interesting to find out what those Macs affected by this issue have in common, but it would be literally searching for the proverbial needle in the haystack.

**Comment by abarraza-grubhub** [comment]
I have the same issue.
Attached screenshots.

My computer is running Monterey v12.1 on an Apple M1 Pro.

I first installed macFUSE using brew and my goal is to use it with s3fs.
I ran the following commands on a terminal with Rosetta enabled.

`brew install macfuse`

`brew install gromgit/fuse/s3fs-mac`

I have installed, uninstalled, and reinstalled, I have done several resets, different combinations of resetting (e.g. first installing macFuse, then reset, installing s3fs, then resetting)... the result is always the same: when I attempt to mount S3 as a drive the prompt requests the permissions and to reset the computer to disable system integrity protection, etc.

I downloaded the [dmg](https://github.com/osxfuse/osxfuse/releases) to install macFUSE, and during the installation, I get the prompt to reset and disable system integrity (attached screenshot).

I haven't wanted to follow this part of the procedure (disabling SIP), hoping there would be a better solution. 

<img width="1304" alt="brew installation" src="https://user-images.githubusercontent.com/95870512/148659965-877eaac0-0cca-4dec-875d-180495848d47.png">
<img width="628" alt="dmg installation" src="https://user-images.githubusercontent.com/95870512/148659968-70325f1c-0136-4687-813a-b8ad1766166e.png">
<img width="670" alt="permissions request " src="https://user-images.githubusercontent.com/95870512/148659969-026f7ed2-bbf5-4b7b-b1d6-5f317d65bbd6.png">
<img width="670" alt="permissions request 2" src="https://user-images.githubusercontent.com/95870512/148659970-49478955-9283-482d-9681-3815288e5531.png">

**Comment by bfleischer** [comment]
@abarraza-grubhub macOS prompts you to enable loading third-party kernel extensions in the recovery environment before you can use third-party kernel extensions like macFUSE. There is no way around this, if you want to use third-party kernel extensions on Apple Silicon Macs. This step is not required on Intel Macs. It's not very intuitive, but that's the way Apple designed the process. Enabling support for loading third-party kernel extensions in recovery mode is NOT disabling System Integrity Protection. System Integrity Protection is a completely different security feature.

**Comment by hukevinxiaochen** [comment]
> So the prevailing instructions coming from this thread seem to be:
> 
> 1. Install latest macFUSE (>=4.2.0)
> 2. restart macOS
> 3. attempt to mount your filesystem (using whatever software you have that relies on macFUSE)
> 
> * IF you get the error "System Extension Blocked"
> 
> 4. Cancel the error dialog
> 5. restart macOS
> 6. attempt once more to mount your filesystem
> 
> * IF you STILL get the error "System Extension Blocked"
> 
> 7. Cancel the error dialog
> 8. uninstall macFUSE
> 9. disable System Integrity Protection - https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection
> 10. restart macOS (as part of that process)
> 11. install macFUSE (while System Integrity Protection is disabled)
> 12. restart macOS (without enabling System Integrity Protection)
> 13. attempt once more to mount your filesystem, and you will _not_ be surprised to get the error "System Extension Blocked"
> 14. **this time** open System Preferences / Security and Approve the macFUSE Extension
> 15. Enable System Integrity Protection
> 16. reboot your macOS
> 17. you should now be able to mount your filesystem without error (but perhaps **with** a little dance of joy?)
> 
> If you are highly pessimistic you _could_ skip straight to step 8, but only a small (but significant) number of cases seem to need such extreme measures, so try the first steps first.

Worked for me on macOS 12.1 and macFUSE 4.2.4 on an Intel-based mac from 2017 recently upgraded to 12.1 without a clean install. Just to be clear, SIP is not disabled permanently. I did disable it temporarily to install macFUSE and work through steps 11-14. I am now able to use Cryptomator (which depends on macFUSE) without issue.

Reading past @artmg 's post, it looks like disabling SIP, whether temporarily or permanently, is not required. Instead, an understanding of system security policies with respect to kernel extensions would probably have saved some headache. Found @bfleischer 's last comment and this [page from apple on kernel extensions](https://support.apple.com/en-za/guide/deployment/depa5fb8376f/web) and this [one](https://support.apple.com/en-za/guide/security/sec8e454101b/web) to be interesting, but confusing. Confusing because they seem to imply that a simple reboot would have done the trick to resolve my issues after first encountering the "System Extension Blocked..." error message, but this did not work for me. Clearly it worked for a good number of people, but it seems there were also folks in my boat.

Agh, sorry I don't have some better insights for you all. Guess I just wanted to say that I appreciated everyone's hard work.

**Comment by gavineadie** [comment]
For what it’s worth, macFUSE is not the only software that has to deal with this.  Rogue Amoeba’s sound applications also need to install such software to give deeper control over managing access the Mac’s sound processing internals.  There’s may be other software that hits this impediment .. certainly macFUSE is in good company.

**Comment by abarraza-grubhub** [comment]
@bfleischer Thank you for the feedback. Sorry for the confusion. 
I restarted my computer, entered recovery mode and enabled the permissions in the attached picture. This seems to have solved my issue. 
I'm sorry there is no way around this. It feels wrong to leave the computer with 'Reduced Security'. However, if I set my computer back to 'Full Security' macFUSE doesn't work anymore. 
Thank you for the help :)

![IMG_0079](https://user-images.githubusercontent.com/95870512/148877994-f66b249e-805f-47be-a418-ef0f9170c751.jpg)

**Comment by bfleischer** [comment]
Enabling "Allow remote management of kernel extension and automatic software updates" is not required for using macFUSE. Only the first option "Allow user management ..." is required.

* The "Reduced Security" mode on Apple Silicon Macs is the default for Intel Macs. There is no "Full Security" mode on Intel Macs. This means an Apple Silicon Mac will not be less secure than any Intel Mac ever shipped. 
* Running in "Reduced Security" mode allows you to load third-party kernel extensions, but none of the extension can be loaded without your consent. Just like with macFUSE you will need to press the "Allow" button in System Preferences and reboot your Mac before any third-party kernel extension can be loaded. You will only be able to load kernel extensions that are signed by the developer and approved by Apple through Apple's notarization service.
* In "Full Security" mode you will only be allowed to install the latest version of macOS. Downgrading to an earlier version of macOS will not be possible. In "Reduced Security" mode you can install older versions of macOS.

TL;DR

"Reduced Security" mode gives you more control over your Mac, but it does not make it less secure, unless you click on every "Allow" button that pops up without questioning it. "Full Security" mode is similar to putting training wheels on your bike. They make it harder to fall, but when you know how to ride a bike, you get along just fine without them. 🙂

**Comment by abarraza-grubhub** [comment]
Thanks @bfleischer, your comment is very informative, helpful and reassuring 👍

**Comment by emmajarv** [comment]
Just wanted to inform that my problem was solved after upgrade to Monterey and reinstallation of macFUSE.

**Comment by connorbrand** [comment]
Thank you @bfleischer, this is super helpful! One thing to note, this "Reduced Security" mode breaks Apple Pay. I'm getting this error message in System Preferences: "Card is unavailable to use with Apple Pay. Apple Pay has been disabled because the security settings of this Mac were modified."

**Comment by bfleischer** [comment]
@connorbrand I'm using Apple Pay on an M1 Mac in Reduced Security mode. It's definitely possible to use Apple Pay and macFUSE at the same time. This issue was raised before in https://github.com/osxfuse/osxfuse/issues/860.

**Comment by GregDunn1953** [comment]
I'm using VeraCrypt (latest) and MacFUSE 4.2.4 on OS 11.6.1, and MacFUSE worked perfectly until the 11.6.1 update (was formerly on 11.5).  I tried the complete procedure that @artmg listed above, and (1) after seeing the kext load error dialog, I do not get the approval option in Preferences, (2) FUSE works fine with SIP disabled, (3) as soon as I re-enable SIP FUSE fails to load again.

I went through this same problem a few months ago on a totally different machine, different OS version, different FUSE version.  What finally fixed it for me was going in and cleaning up the kext_policy and StagedExtensions directories/files named by @bfleischer in the earlier messages.  Unfortunately, I can't find my notes as to what I specifically changed, so I'm going to have to look at the forums here again and try to puzzle it out.

Edit: found my notes.  With SIP off, I changed the KernelExtensionManagement/ and KernelExtensionManagement/Staging directories to have the "restricted" flag and then rebooted.  Again, it works with SIP disabled but not enabled.  The problem lies somewhere else this time.

**Comment by cdevers-es** [comment]
Following up on [my query from last month](https://github.com/osxfuse/osxfuse/issues/828#issuecomment-1007099303), the customer who reported the FUSE kernel extension loading problem on “all” of their macOS 11.6.2 Big Sur workstations has finally gotten back to us, indicating that the problem is now resolved for the Macs he manages.

Earlier, we had the customer do this, which he claims was unsuccessful:

1. Disable SIP (`csrutil disable` in Recovery)
2. Reboot and try to load the software that uses MacFUSE
3. If that fails, run `csrutil clear` from macOS Recovery, reboot and retry
4. If loading FUSE is now successful, reenable SIP (`csrutil enable` from Recovery)

The customer claims that he tried these steps, but they did not resolve the problem. 

We then had another customer report a similar pattern, and they used the following procedure to resolve the issue:

1. Uninstall the software that uses MacFUSE
2. Empty out system caches (`/Library/Caches` & `/System/Library/Caches`)
3. Re-enable SIP by using `csrutil enable` from macOS Rescue Mode
4. Reinstall the software

The first customer reports today that this procedure worked for them as well.

This seems to implicate something in one of the system `Caches` directory, but unfortunately, we don’t have further detail to narrow down which specific thing(s) in there interfered with the FUSE software, and we don’t have steps to reproduce the problem on a “pristine” Mac.

For that matter, since we had these people try several different steps, and the reports we got back were, more or less, “it’s fixed now”, we’re a little unclear on _which_ steps ended up being key to resolving the problem. 

In any case, if we encounter this again, we now appear to have a viable approach to resolving this. We’ll try to hone the steps to both reproduce & resolve the problem, and can report back if we hit upon a “distilled” recipe that seems to work consistently.

**Comment by ghost** [comment]
I would assume that those steps lead to rebuilding file kextallow, which includes bundle-ids: 

```
$ sudo grep fuse /System/Library/Caches/com.apple.kext.caches/kextallow 
<string>com.github.osxfuse.filesystems.osxfuse</string>
<string>io.macfuse.filesystems.macfuse</string>
```

**Comment by GregDunn1953** [comment]
Just tried @cdevers-es solution.  No change.  Then I tried it again, but uninstalled MacFUSE instead of VeraCrypt. After re-enabling SIP I installed MacFUSE again, and when I tried to load it I finally(!) got the "allow" option in Preferences.  I hit the button, followed instructions to reboot again, and... nope.  MacFUSE still fails to load and the "allow" button is gone again.

I'm going to try both sets of steps, from the beginning, and see if it does anything different.

Edit: No, exactly the same thing happened.  I have to have SIP disabled or at least kext validation turned off, or MacFUSE will not load.  After the initial "allow" in Preferences, I don't get the button ever again.

**Comment by Martin-Pitt** [comment]
I was referring to this github issue thread during research for a similar issue in other software (Egnyte). I don't know if MacFUSE has a similar problem but the symptoms were identical to mine. I found another thread which helped resolve the issue by removing kext for other macOS versions and only keeping the latest for mine. You can check via System Information -> Extensions.

https://boxcryptor.community/d/17031-apple-silicon/44
> In the end the major blocker was really "only" that the new macOS kernel extension management is **confused by multiple included kernel extensions for the different macOS versions** (which was never an issue in the past). Once we removed the kernel extensions for the older macOS versions, everything turned green again 🙂

**Comment by GregDunn1953** [comment]
I checked, and there is only one copy of MacFUSE loaded, and it's the correct version. (Obviously I have SIP disabled, or it wouldn't be loading at all)

**Comment by jjstickel** [comment]
I am also getting "System Extension Blocked", but no "allow button" in system preferences. This is macOS 11.6.3 and macFUSE 4.2.4. It worked with SIP disabled, but not again after SIP is re-enabled.

**Comment by jjstickel** [comment]
> I am also getting "System Extension Blocked", but no "allow button" in system preferences. This is macOS 11.6.3 and macFUSE 4.2.4. It worked with SIP disabled, but not again after SIP is re-enabled.

It seems like I got it working! I basically did something similar to what is described here (in the first comment by CodeBlazer):
https://gist.github.com/fcoclavero/431123c7708e42de63eb75264a44de02

The step that I didn't see in the discussion here and was the key for me is (in Recovery mode):
`/usr/sbin/spctl kext-consent add 3T5GSNBU6W`
I tried all the other steps previously, and I was till getting the "System Extension Blocked" dialog box when SIP was enabled. To get the correct code for the macfuse kernel extension, I used this command (in normal boot mode):
`sudo sqlite3 /private/var/db/SystemPolicyConfiguration/KextPolicy "select * from kext_policy;"`
I had to write it down to use with the command above in Recover mode. Back in normal boot mode, you can try to load the macfuse extension with:
`sudo kextload /Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext`
I also did the sequence of steps with disabling and re-enabling SIP all over again, but I wonder now if that is necessary. The `kext-consent` command seems to be the key.

**Comment by GregDunn1953** [comment]
Still no bueno.  Added the developer ID without a problem (and yes, I checked to make sure it was the same value on my machine).

sudo kextload /Library/Filesystems/macfuse.fs/Contents/Extensions/11/macfuse.kext  worked if SIP was disabled, but not if it was enabled.  And if it failed (the error message asked for a reboot, which didn't help), so did the loading of MacFUSE requested by Veracrypt.  Enabling SIP --without kext is the only way it will load properly.

**Comment by brokolyce** [comment]
> Enabling "Allow remote management of kernel extension and automatic software updates" is not required for using macFUSE. Only the first option "Allow user management ..." is required.
> 
> * The "Reduced Security" mode on Apple Silicon Macs is the default for Intel Macs. There is no "Full Security" mode on Intel Macs. This means an Apple Silicon Mac will not be less secure than any Intel Mac ever shipped.
> * Running in "Reduced Security" mode allows you to load third-party kernel extensions, but none of the extension can be loaded without your consent. Just like with macFUSE you will need to press the "Allow" button in System Preferences and reboot your Mac before any third-party kernel extension can be loaded. You will only be able to load kernel extensions that are signed by the developer and approved by Apple through Apple's notarization service.
> * In "Full Security" mode you will only be allowed to install the latest version of macOS. Downgrading to an earlier version of macOS will not be possible. In "Reduced Security" mode you can install older versions of macOS.
> 
> TL;DR
> 
> "Reduced Security" mode gives you more control over your Mac, but it does not make it less secure, unless you click on every "Allow" button that pops up without questioning it. "Full Security" mode is similar to putting training wheels on your bike. They make it harder to fall, but when you know how to ride a bike, you get along just fine without them. 🙂

Apple states on their support page (https://support.apple.com/en-ng/guide/security/sec7d92dc49f/web):
"developers are being strongly encouraged to adopt system extensions before kext support is removed from macOS for future Mac computers with Apple silicon."

You stated here (https://github.com/osxfuse/osxfuse/issues/828#issuecomment-1001817061):
"There is no other way to use third-party file systems without "lowering" security settings in recover mode because Apple does not provide a non-kernel API for developing full-featured file systems."

Does this mean that MacFUSE will stop working in the future when Apple decommissions the kernel extensions as there won't be a system extension for MacFUSE to use ?

**Comment by cdevers-es** [comment]
[brokolyce](https://github.com/brokolyce) —

> Does this mean that MacFUSE will stop working in the future when Apple decommissions the kernel extensions as there won't be a system extension for MacFUSE to use ?

This is a FAQ.

Yes, Apple is phasing out support for most “kernel” extensions, and wants developers to switch to “system” extensions.

No, this does not yet affect MacFUSE, because Apple has not yet provided suitable functionality that would enable implementation of filesystems as system extensions. 

Yes, Apple is aware of this, and is working on it (or so we’ve been told).

Yes, MacFUSE will switch to the new system extension model if & when Apple provides a suitable way to do so.

**Comment by slaqr-mel** [comment]
> 1. Uninstall the software that uses MacFUSE
> 2. Empty out system caches (`/Library/Caches` & `/System/Library/Caches`)
> 3. Re-enable SIP by using `csrutil enable` from macOS Rescue Mode
> 4. Reinstall the software
> 
> The first customer reports today that this procedure worked for them as well.

I can confirm that [this procedure](https://github.com/osxfuse/osxfuse/issues/828#issuecomment-1027348679) also worked for me as well. We spent about 6 hours of troubleshooting on this, refusing to believe that disabling SIP would be the solution (I even performed the nuclear option of completely removing the Mosyle MDM profiles from our affected machine, thinking there might be an unknown TCC issue that caused the issue). But lo and behold, this solution from [cdevers-es](https://github.com/cdevers-es) ended up being the only thing that worked.

FWIW, this was on a 2017 iMac, running macOS 12.3.1 (recently upgraded directly to Monterey from Mojave 10.14.6), macFUSE 4.2.5.

**Comment by RichardLee0211** [comment]
mystery system response when it doesn't do what they say. 
the error persists after reboot on macOS 11.6.7. tried 20 times, and clear system caches did the trick. 
hope a little log helps diagnose, and people on this are awesome. 

```shell

kmutil log stream

2022-06-15 20:53:07.002858-0400 0x5fd2     Default     0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] existing, approved auxiliary kext collection direct loads:
	Kext com.softraid.driver.SoftRAID v6.0 in executable kext bundle com.softraid.driver.SoftRAID at /Library/Extensions/SoftRAID.kext
	Kext io.macfuse.filesystems.macfuse v2085.16 in executable kext bundle io.macfuse.filesystems.macfuse at /Library/Filesystems/macfuse.fs/Contents/Extensions/10.12/macfuse.kext
	Kext com.vmware.kext.vmnet v1780.15.03 in executable kext bundle com.vmware.kext.vmnet at /Applications/VMware Fusion.app/Contents/Library/kexts/vmnet.kext
	Kext com.apple.nke.rvi v2.1.0 in executable kext bundle com.apple.nke.rvi at /Library/Apple/System/Library/Extensions/RemoteVirtualInterface.kext
	Kext com.vmware.kext.vmx86 v1780.15.03 in executable kext bundle com.vmware.kext.vmx86 at /Applications/VMware Fusion.app/Contents/Library/kexts/vmmon.kext
	Kext org.virtualbox.kext.VBoxNetAdp v6.1.18 in executable kext bundle org.virtualbox.kext.VBoxNetAdp at /Library/Application Support/VirtualBox/VBoxNetAdp.kext
	Kext com.highpoint-tech.kext.HighPointRR v4.22.1 in executable kext bundle com.highpoint-tech.kext.HighPointRR at /Library/Extensions/HighPointRR.kext
	Kext org.virtualbox.kext.VBoxUSB v6.1.18 in executable kext bundle org.virtualbox.kext.VBoxUSB at /Library/Application Support/VirtualBox/VBoxUSB.kext
	Kext org.virtualbox.kext.VBoxDrv v6.1.18 in executable kext bundle org.virtualbox.kext.VBoxDrv at /Library/Application Support/VirtualBox/VBoxDrv.kext
	Kext com.Cycling74.driver.Soundflower v2 in executable kext bundle com.Cycling74.driver.Soundflower at /Library/Extensions/Soundflower.kext
	Kext com.silabs.driver.CP210xVCPDriver64 v3.0.0d1 in executable kext bundle com.silabs.driver.CP210xVCPDriver64 at /Library/Extensions/SiLabsUSBDriver64.kext
	Kext com.vmware.kext.vmioplug.19.9.0 v19.9.0 in executable kext bundle com.vmware.kext.vmioplug.19.9.0 at /Applications/VMware Fusion.app/Contents/Library/kexts/vmioplug.kext
	Kext com.highpoint-tech.kext.HighPointIOP v4.4.5 in executable kext bundle com.highpoint-tech.kext.HighPointIOP at /Library/Extensions/HighPointIOP.kext
	Kext org.virtualbox.kext.VBoxNetFlt v6.1.18 in executable kext bundle org.virtualbox.kext.VBoxNetFlt at /Library/Application Support/VirtualBox/VBoxNetFlt.kext
2022-06-15 20:53:07.003146-0400 0x5fd2     Default     0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] existing, loadable, and approved auxiliary kext collection direct loads:
	Kext io.macfuse.filesystems.macfuse v2085.16 in executable kext bundle io.macfuse.filesystems.macfuse at /Library/Filesystems/macfuse.fs/Contents/Extensions/10.12/macfuse.kext
2022-06-15 20:53:07.003289-0400 0x5fd2     Default     0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] existing approved auxiliary kext collection direct load dependencies:
2022-06-15 20:53:07.004713-0400 0x5fd2     Default     0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] new auxiliary kext collection candidates:
	Kext com.softraid.driver.SoftRAID v6.0 in executable kext bundle com.softraid.driver.SoftRAID at /Library/Extensions/SoftRAID.kext (existing)
	Kext io.macfuse.filesystems.macfuse v2085.16 in executable kext bundle io.macfuse.filesystems.macfuse at /Library/Filesystems/macfuse.fs/Contents/Extensions/10.12/macfuse.kext (existing)
	Kext com.vmware.kext.vmnet v1780.15.03 in executable kext bundle com.vmware.kext.vmnet at /Applications/VMware Fusion.app/Contents/Library/kexts/vmnet.kext (existing)
	Kext com.apple.nke.rvi v2.1.0 in executable kext bundle com.apple.nke.rvi at /Library/Apple/System/Library/Extensions/RemoteVirtualInterface.kext (existing)
	Kext com.vmware.kext.vmx86 v1780.15.03 in executable kext bundle com.vmware.kext.vmx86 at /Applications/VMware Fusion.app/Contents/Library/kexts/vmmon.kext (existing)
	Kext org.virtualbox.kext.VBoxNetAdp v6.1.18 in executable kext bundle org.virtualbox.kext.VBoxNetAdp at /Library/Application Support/VirtualBox/VBoxNetAdp.kext (existing)
	Kext com.highpoint-tech.kext.HighPointRR v4.22.1 in executable kext bundle com.highpoint-tech.kext.HighPointRR at /Library/Extensions/HighPointRR.kext (existing)
	Kext org.virtualbox.kext.VBoxUSB v6.1.18 in executable kext bundle org.virtualbox.kext.VBoxUSB at /Library/Application Support/VirtualBox/VBoxUSB.kext (existing)
	Kext org.virtualbox.kext.VBoxDrv v6.1.18 in executable kext bundle org.virtualbox.kext.VBoxDrv at /Library/Application Support/VirtualBox/VBoxDrv.kext (existing)
	Kext com.Cycling74.driver.Soundflower v2 in executable kext bundle com.Cycling74.driver.Soundflower at /Library/Extensions/Soundflower.kext (existing)
	Kext com.silabs.driver.CP210xVCPDriver64 v3.0.0d1 in executable kext bundle com.silabs.driver.CP210xVCPDriver64 at /Library/Extensions/SiLabsUSBDriver64.kext (existing)
	Kext com.vmware.kext.vmioplug.19.9.0 v19.9.0 in executable kext bundle com.vmware.kext.vmioplug.19.9.0 at /Applications/VMware Fusion.app/Contents/Library/kexts/vmioplug.kext (existing)
	Kext com.highpoint-tech.kext.HighPointIOP v4.4.5 in executable kext bundle com.highpoint-tech.kext.HighPointIOP at /Library/Extensions/HighPointIOP.kext (existing)
	Kext org.virtualbox.kext.VBoxNetFlt v6.1.18 in executable kext bundle org.virtualbox.kext.VBoxNetFlt at /Library/Application Support/VirtualBox/VBoxNetFlt.kext (existing)
2022-06-15 20:53:07.005524-0400 0x5fd2     Default     0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] resolved kext load request:
	0 direct platform kext loads,
	1 direct auxiliary kext loads,
	14 auxkc candidates (building not required)
	0 awaiting reboot (already approved)
	0 approvals needed
2022-06-15 20:53:07.005618-0400 0x5fd2     Default     0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] direct loads:
	Kext io.macfuse.filesystems.macfuse v2085.16 in executable kext bundle io.macfuse.filesystems.macfuse at /Library/Filesystems/macfuse.fs/Contents/Extensions/10.12/macfuse.kext
2022-06-15 20:53:07.005768-0400 0x5fd2     Default     0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] auxKC filesystem check: Kext io.macfuse.filesystems.macfuse v2085.16 in executable kext bundle io.macfuse.filesystems.macfuse at /Library/Filesystems/macfuse.fs/Contents/Extensions/10.12/macfuse.kext found at /Library/Filesystems/macfuse.fs/Contents/Extensions/10.12/macfuse.kext
2022-06-15 20:53:07.005880-0400 0x5fd2     Default     0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:KernelClient] loading extension from in-kernel fileset: io.macfuse.filesystems.macfuse (will start, will match)
2022-06-15 20:53:07.012573-0400 0x5fd2     Default     0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:Kernel] (kernel): Kext io.macfuse.filesystems.macfuse did not start (return code 0x5).
2022-06-15 20:53:07.012611-0400 0x5fd2     Error       0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:Kernel] (kernel): Kext io.macfuse.filesystems.macfuse start failed (result 0x5).
2022-06-15 20:53:07.012635-0400 0x5fd2     Error       0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:Kernel] (kernel): Kext io.macfuse.filesystems.macfuse failed to load (0xdc008017).
2022-06-15 20:53:07.012645-0400 0x6238     Default     0x0                  95     0    kernelmanagerd: Received kext unload notification: io.macfuse.filesystems.macfuse
2022-06-15 20:53:07.012653-0400 0x5fd2     Error       0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:Kernel] (kernel): Failed to load kext io.macfuse.filesystems.macfuse (error 0xdc008017).
2022-06-15 20:53:07.012721-0400 0x5fd2     Default     0xc318               95     0    kernelmanagerd: [com.apple.kernelmanagerd.logging:LoadRequestResolution] loadExtension for Kext io.macfuse.filesystems.macfuse v2085.16 in executable kext bundle io.macfuse.filesystems.macfuse at /Library/Filesystems/macfuse.fs/Contents/Extensions/10.12/macfuse.kext failed with: Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)
2022-06-15 20:53:07.013313-0400 0x5fd2     Error       0xc318               95     0    kernelmanagerd: failed to load/rebuild extensions: Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)

```

> 1. Uninstall the software that uses MacFUSE
> 2. Empty out system caches (/Library/Caches & /System/Library/Caches)
> 3. Re-enable SIP by using csrutil enable from macOS Rescue Mode
> 4. Reinstall the software
> The first customer reports today that this procedure worked for them as well.

**Comment by Lebostein** [comment]
> So the prevailing instructions coming from this thread seem to be:
>     1. Install latest macFUSE (>=4.2.0)
>     2. restart macOS
>     3. attempt to mount your filesystem (using whatever software you have that relies on macFUSE)
>     4. Cancel the error dialog
>     5. restart macOS
>     6. attempt once more to mount your filesystem
>     7. Cancel the error dialog
>     8. uninstall macFUSE
>     9. disable System Integrity Protection - https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection
>     10. restart macOS (as part of that process)
>     11. install macFUSE (while System Integrity Protection is disabled)
>     12. restart macOS (without enabling System Integrity Protection)
>     13. attempt once more to mount your filesystem, and you will _not_ be surprised to get the error "System Extension Blocked"
>     14. **this time** open System Preferences / Security and Approve the macFUSE Extension
>     15. Enable System Integrity Protection
>     16. reboot your macOS
>     17. you should now be able to mount your filesystem without error (but perhaps **with** a little dance of joy?)

I have the same problem with Mac OS 13.2. I have tried the solution above. But I stuck in point 14 "**this time** open System Preferences / Security and Approve the macFUSE Extension". How exactly is this supposed to work? I can't accept anything from macFuse in the Preferences / Security settings at this step....

**Comment by ferdnyc** [comment]
@Lebostein

> I have the same problem with Mac OS 13.2. 

On a Silicon (M1) or Intel Mac? The requirements for enabling kernel extension loading are very different between the two. I'm going to assume it's an Intel Mac, because if not the prompts you encountered would have been different enough to have thrown you before step 14. But in case I'm wrong, the process for Silicon-based Macs is at [the macFUSE Wiki](https://github.com/macfuse/macfuse/wiki/Getting-Started#enabling-support-for-third-party-kernel-extensions-apple-silicon-macs).

But assuming it's an Intel Mac...

> I have tried the solution above. But I stuck in point 14 "**this time** open System Preferences / Security and Approve the macFUSE Extension". How exactly is this supposed to work? I can't accept anything from macFuse in the Preferences / Security settings at this step....

What you're _supposed_ to see at that point is something similar to this screenshot, also from that wiki page:

<img width="780" alt="186746692-87af993b-d1e6-4136-87fb-fe0949d6c813" src="https://user-images.githubusercontent.com/538020/218236221-ee130d46-32d8-46d0-bd99-f72eac44dd08.png">

If you're **not** seeing that message with "Allow" button, some users have reported that this helps:

1. Reboot to recovery mode again
2. Run all of these commands, in a Terminal while in recovery:
   ```bash
   # Disable SIP, if it's not already disabled
   csrutil disable
   # Clear protection caches
   csrutil clear
   # Authorize macFUSE kext loading
   /usr/sbin/spctl kext-consent add 3T5GSNBU6W
   # Verify that it's on the list
   /usr/sbin/spctl kext-consent list
   ```
3. The last command should show "3T5GSNBU6W" as an allowed identifier
4. Reboot back into normal mode
5. Try mounting a macFUSE filesystem
6. If a block message still comes up, look for an "Allow" button in System Preferences / Security & Privacy

<s>Also, this is a weird one (and I don't see it having been mentioned here before), but according to this article from Howard Oakley, [macOS won't show kext authorization prompts if there are any external disks mounted](https://eclecticlight.co/2022/04/19/booting-a-mac-studio-from-an-external-ssd-and-what-it-doesnt-solve/). So, if you have any USB devices connected that can be mounted as disks, try removing those temporarily before attempting to load macFUSE.</s>

**Comment by JZADC** [comment]
Hello 
anyone was able to solve the deployment via jamf without disabling SIP on M1/M2 MacBooks with MacOS Ventura?
THX in Advance
J

**Comment by Clovenhoofblues** [comment]
> 
You can create a config which pre-approves MacFuse (system ad kernel extensions) based on the team id (3T5GSNBU6W) and then add 'allowed system extension' (io.macfuse.filesystems.macfuse). But, keep in mind that there's a bug in Jamf which means some DEP Mac's which haven't been enrolled correctly won't approve of the config. In that case you would either go down the SIP approval route via "Disc Recovery". Or, erase and reinstall the Mac.

**Comment by ddon** [comment]
This is 2023 now, still getting this message... has anybody resolved this in macOS Venture 13.3? I have noticed that "Security & Privacy" is now called "Privacy & Security", and screen looks completely different and I don't see anything there to press Allow. Any fresh instructions?

**Comment by Qualia-Li** [comment]
> This is 2023 now, still getting this message... has anybody resolved this in macOS Venture 13.3? I have noticed that "Security & Privacy" is now called "Privacy & Security", and screen looks completely different and I don't see anything there to press Allow. Any fresh instructions?

same here

**Comment by bfleischer** [comment]
@ddon, @Qualia-Li 
Simply install the latest version of macFUSE and follow the instructions on https://github.com/macfuse/macfuse/wiki/Getting-Started.

**Comment by luco** [comment]
@bfleischer Should I enable the full security in Startup Security Utility again after installing FUSE?

EDIT

Turning SIP to Reduced security makes FUSE works, but when enabling again to Full, it doesn't.

**Comment by frathe** [comment]
So there is no way to use osxfuse without lowering system security? Guess I have to live without osxfuse for now.

**Comment by bfleischer** [comment]
@frathe By Apple's design there is no way to use the macOS file system API without "lowering" system security. I'm using quotation marks because, depending on your point of view, system security is only affected marginally. You get prompted to allow loading third party kernel extensions whenever an attempt is made to load such a kernel extension. In full security mode you aren't prompted and the request is denied automatically. Full security mode takes the choice away from you.

**Comment by frathe** [comment]
@bfleischer It is not that I don't trust myself to make the right decision, but I am using a managed device and I have to stick to our security policies. So there sadly is no way to get it running for me.

**Comment by Clovenhoofblues** [comment]
If it's a managed device the kernel extension can be added as an exception.

**Comment by frathe** [comment]
Thought I did that with `/usr/sbin/spctl kext-consent add 3T5GSNBU6W` or is there something else that has to be done?

**Comment by Clovenhoofblues** [comment]
> Thought I did that with `/usr/sbin/spctl kext-consent add 3T5GSNBU6W` or is there something else that has to be done?

If it's a managed device, then the exception would need to be added by IT.

**Comment by adamency** [comment]
An awful lot of bad advice (esp. about disabling System Integrity Protection...) has been shared in this thread while the official wiki already provides the correct solution to this issue:

# Official Documentation

## https://github.com/macfuse/macfuse/wiki/Getting-Started#enabling-support-for-third-party-kernel-extensions-apple-silicon-macs

@artmg Please delete the part of your message that recommends removing System Integrity Protection. It is **never** needed, utterly overkill and very dangerous to inexperienced users. What is needed is described in the link above.

It is even officially addressed in that [same page](https://github.com/macfuse/macfuse/wiki/Getting-Started#notes):

> macFUSE does not require you to disable Gatekeeper or System Integrity Protection. All official macFUSE releases are digitally signed and approved by Apple's Notary Service. This means macFUSE is compatible with Gatekeeper and System Integrity Protection.

PS: but it's understandable, the documentation of this project is all over the place...

**Comment by ferdnyc** [comment]
@adamency 

That's **not** why it's "understandable."

> An awful lot of bad advice (esp. about disabling System Integrity Protection...) has been shared in this thread while the official wiki already provides the correct solution to this issue

**NOW**, it does. This issue is 3.5 years old. If you look at the history of that wiki page, the information you're pointing to was added either this year or last year, largely **BASED ON** the discussions that took place here.

In fact, as recently as March 11 of this year, that page contained the following:

> * Recent version of macOS do not support loading third-party kernel extensions when booting from external volumes. There is no known workaround. This is a limitation of macOS, not macFUSE.
> 
> * If the above procedure does not work for you and you are are asked to allow loading the macFUSE kernel extension again even so you just did, you are most likely running into a macOS bug. Some users recommend disabling System Integrity Protection to get the kernel extension to load on affected Macs. While this seems to work reliably, it is not recommended. Disabling System Integrity protection bypasses the macOS bug, but it also reduces the security of your Mac greatly.

...It wasn't until April 14 (more recently than any message here except yours) that the wiki was updated to say:

> * In case you are prompted to allow loading the macFUSE kernel extension again and again even though you clicked the "Allow" button and restarted your Mac when prompted to, you are running into a macOS bug. Starting with version 4.7.1, macFUSE contains a workaround for this issue.

**Comment by bfleischer** [comment]
Disabling System Integrity Protection (SIP) was never a good idea. It might mask an underlying issue, but it was never a requirement for using macFUSE. If you scroll up in this thread, you will find my posts from 2021 stating exactly that.

Apple rewrote the kext manager subsystem of macOS for macOS 11 and introduced a lot of issues with unforeseen side effects in the process. macFUSE contains several workarounds to deal with some of those effects. Some of the macOS bugs still exist today. I explained this on many occasions, but people still kept suggesting disabling SIP or, even worse, stating that it was a requirement for using macFUSE ... in many cases without providing any context or explaining the risks of disabling SIP.

I created the Getting Started document and put a link to it in the installer and the "allow" prompt to make it easier for new users to install macFUSE successfully. Most of the information in the document is not new but has been "all over the place" as @adamency put it.

**Comment by artmg** [comment]
I have amended the comment as requested
